function fitMeasuredGamma(fileName)

% Created for files generated by gammaAnalysis. Uses PowerLawFit

measuredData = readmatrix(fileName); % Read data as matrix
measuredData = measuredData(:, 21); % Read only the grand mean column of the file
objectiveGreyLevels = zeros(8, 1); % Create object for grey levels

    for i = 1:8
        objectiveGreyLevels(i) = i/9; % Calculate grey-levels for each halftone pattern
    end

PowerLawFit(measuredData, objectiveGreyLevels) % Use PowerLawFit to compare
end